### PR TITLE
Calendar selected cells

### PR DESCRIPTION
**Pull request by jordanF0ster**
selecting a day on the calendar shows all the events in the table view below that start on that day

### CODE REVIEW

**Review by lucyajiang — APPROVED** [review]
Looks good! Why is date comps set to date + 1 again?

**Comment by jordanF0ster** [comment]
> Looks good! Why is date comps set to date + 1 again?

i'm filtering by using a range with nspredicate, the first date component is set to the selected date with an hour of 0 (12AM). This allows for me to find all the dates that occur after the date from the date component with this line `@"eventDate >= %@", date` and then i change day to day +1 in order to find all the dates that occur before the next day with `@"eventDate <= %@", date`.

**Review by sophiakaz — APPROVED** [review]
looks good!

**Review by lucyajiang — APPROVED** [review]
Wow ternary

**Pull request merged**
